return {}
-- return {
-- 	"nvim-treesitter/nvim-treesitter-textobjects",
-- 	lazy = true,
-- 	opts = {
-- 		textobjects = {
-- 			-- select = {
-- 			-- 	enable = true,
-- 			--
-- 			-- 	-- Automatically jump forward to textobj, similar to targets.vim
-- 			-- 	lookahead = true,
-- 			-- 	keymaps = {
-- 			-- 		-- You can use the capture groups defined in textobjects.scm
-- 			-- 		["aa"] = { query = "@assignment.outer", desc = "Select outer part of an assignment" },
-- 			-- 		["i="] = { query = "@assignment.inner", desc = "Select inner part of an assignment" },
-- 			-- 		["l="] = { query = "@assignment.lhs", desc = "Select left hand side of an assignment" },
-- 			-- 		["r="] = { query = "@assignment.rhs", desc = "Select right hand side of an assignment" },
-- 			-- 		["if"] = { query = "@function.inner", desc = "Select inner part of a function" },
-- 			-- 		["af"] = { query = "@function.outer", desc = "Select outer part of a function" },
-- 			-- 	},
-- 			-- },
--
-- 			-- swap = {
-- 			-- 	enable = true,
-- 			-- 	swap_next = {
-- 			-- 		["<leader>np"] = "@parameter.inner",
-- 			-- 		["<leader>nm"] = "@function.inner",
-- 			-- 	},
-- 			-- 	swap_previous = {
-- 			-- 		["<leader>pp"] = "@parameter.inner",
-- 			-- 		["<leader>pm"] = "@function.inner",
-- 			-- 	},
-- 			-- },
--
-- 			-- move = {
-- 			-- 	enable = true,
-- 			-- 	set_jumps = true, -- whether to set jumps in the jumplist
-- 			-- 	goto_next = {
-- 			-- 		["]m"] = "@function.outer",
-- 			-- 	},
-- 			-- 	goto_previous = {
-- 			-- 		["[m"] = "@function.outer",
-- 			-- 	},
-- 			-- },
-- 		},
-- 	},
-- 	config = function(_, opts)
-- 		require("nvim-treesitter.configs").setup(opts)
--
-- 		local ts_repeat = require("nvim-treesitter.textobjects.repeatable_move")
--
-- 		-- Repeat movement with ; and ,
-- 		-- ensure ; goes forward and , goes backward regardless of the last direction
-- 		-- vim.keymap.set({ "n", "x", "o" }, ";", ts_repeat.repeat_last_move_next)
-- 		-- vim.keymap.set({ "n", "x", "o" }, ",", ts_repeat.repeat_last_move_previous)
--
-- 		-- vim way: ; goes to the direction you were moving.
-- 		vim.keymap.set({ "n", "x", "o" }, ";", ts_repeat.repeat_last_move)
-- 		vim.keymap.set({ "n", "x", "o" }, ",", ts_repeat.repeat_last_move_opposite)
--
-- 		-- Optionally, make builtin f, F, t, T also repeatable with ; and ,
-- 		vim.keymap.set({ "n", "x", "o" }, "f", ts_repeat.builtin_f)
-- 		vim.keymap.set({ "n", "x", "o" }, "F", ts_repeat.builtin_F)
-- 		vim.keymap.set({ "n", "x", "o" }, "t", ts_repeat.builtin_t)
-- 		vim.keymap.set({ "n", "x", "o" }, "T", ts_repeat.builtin_T)
-- 	end,
-- }
